import React from 'react'
import Head from 'next/head'
import Overview from '../../../../components/Overview/Overview.jsx'
import collectionService from '../../../../services/collectionService'
import pictureService from '../../../../services/pictureService'
import PropTypes from 'prop-types'
import { getPlaiceholder } from 'plaiceholder'
import Layout from '../../../../components/Layout/Layout.jsx'

const PicturePage = ({ pictureData }) => {
  const title = `${process.env.NEXT_PUBLIC_APP_TITLE} | Page photo`
  return (
    <>
      <Head>
        <title key='title'>{title}</title>
        <meta
          key='description'
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <Layout>
        <Overview pictureData={pictureData} />
      </Layout>
    </>
  )
}

export const getStaticPaths = async () => {
  const collections = await collectionService.loadAllCollections()

  const paths = await Promise.all(
    collections.map(async collection => {
      const pictures = await pictureService.loadPicturesByCollection(
        collection.slug,
      )
      return pictures.map(picture => ({
        params: { slug: collection.slug, id: picture.id.toString() },
      }))
    }),
  ).then(res => res.flat())

  return {
    paths,
    fallback: 'blocking',
  }
}

export async function getStaticProps({ params }) {
  const pictureData = await pictureService.loadPictureById(parseInt(params.id))

  const { base64 } = await getPlaiceholder(pictureData._embedded['wp:featuredmedia'][0].source_url) 

  pictureData.base64 = base64

  return {
    props: {
      pictureData,
    },
    revalidate: 10,
  }
}

PicturePage.propTypes = {
  pictureData: PropTypes.object.isRequired,
}

export default PicturePage
