import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import PropTypes from 'prop-types'
import Grid from '../../components/Grid/Grid'
import collectionService from '../../services/collectionService'
import pictureService from '../../services/pictureService'
import { getPlaiceholder } from 'plaiceholder'

const Collection = ({ pictures }) => {
  const router = useRouter()
  const { slug } = router.query
  const capitalizedSlug = slug?.charAt(0)?.toUpperCase() + slug?.slice(1)

  const title = `${process.env.NEXT_PUBLIC_APP_TITLE} | ${capitalizedSlug}`

  return (
    <>
      <Head>
        <title key='title'>{title}</title>
        <meta
          key='description'
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <Grid pictures={pictures} />
    </>
  )
}

export async function getStaticPaths() {
  const collections = await collectionService.loadAllCollections()
  const paths = collections.map(collection => ({
    params: { slug: collection.slug },
  }))
  return {
    paths,
    fallback: 'blocking',
  }
}

export async function getStaticProps({ params }) {
  const pictures = await pictureService.loadPicturesByCollection(params.slug)

  const picturesWithBase64 = await Promise.all(pictures.map(async picture => {
    const { base64 } = await getPlaiceholder(picture._embedded['wp:featuredmedia'][0].media_details.sizes.full.source_url)
    picture.base64 = base64
    return picture
  }))

  picturesWithBase64.sort((a, b) => {
    const priorityA = a.acf.priority !== undefined ? parseInt(a.acf.priority) : 999
    const priorityB = b.acf.priority !== undefined ? parseInt(b.acf.priority) : 999

    return priorityA - priorityB
  })

  return {
    props: {
      pictures: picturesWithBase64,
    },
    revalidate: 10,
  }
}

Collection.propTypes = {
  pictures: PropTypes.array.isRequired,
}

export default Collection
