import Head from 'next/head'
import Stripe from '../components/Stripe/Stripe.jsx'
import Loader from '../components/Loader/Loader.jsx'
import ArrowButton from '../components/ArrowButton/ArrowButton.jsx'
import React, { useEffect, useState, useRef } from 'react'
import collectionService from '../services/collectionService'
import PropTypes from 'prop-types'
import useDraggable from '../hooks/useDraggable'
import { useAppContext } from '../context/state'
import Layout from '../components/Layout/Layout.jsx'
import websiteService from '../services/websiteService'

const Home = ({ collections, description }) => {
  const [isVisible, setIsVisible] = useState(true)
  const [count, setCount] = useState(0)
  const [countImgLoaded, setCountImgLoaded] = useState(0)
  const [loading, setLoading] = useState(true)
  const [isMobile, setIsMobile] = useState(false)
  const collectionList = useRef(null)

  const Context = useAppContext()
  const { isExpanded } = Context

  useDraggable(collectionList)

  const title = `${process.env.NEXT_PUBLIC_APP_TITLE} | Site internet`

  const handleScroll = e => {
    setCount(e.target.scrollLeft)
    if (count > 60) {
      setIsVisible(false)
    }
  }

  const handleResize = () => {
    document.documentElement.clientWidth < 768
      ? setIsMobile(true)
      : setIsMobile(false)
  }

  useEffect(() => {
    setCountImgLoaded(0)
    setLoading(true)
    window.addEventListener('resize', handleResize)
    handleResize()

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [])

  useEffect(() => {
    if(countImgLoaded === collections.length){
      setLoading(false)
    }
  }, [countImgLoaded])

  return (
    <>
      <Head>
        <title key='title'>{title}</title>
        <meta
          key='description'
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <Layout description={description}>
        {loading && <Loader />}
        <div
          ref={collectionList}
          className='collection-list'
          onScroll={isVisible ? handleScroll : undefined}>
          {collections?.map(collection => (
            <Stripe
              key={collection?.id}
              isMobile={isMobile}
              slug={collection?.slug}
              name={collection?.name}
              desktop_img_url={collection?.acf.desktop_image}
              mobile_img_url={
                collection?.acf.mobile_image ? collection.acf.mobile_image : ''
              }
              setCountImgLoaded={setCountImgLoaded}
            />
          ))}
          {isExpanded && <ArrowButton isVisible={isVisible} />}
        </div>
      </Layout>
    </>
  )
}

Home.propTypes = {
  collections: PropTypes.array.isRequired,
  description: PropTypes.string.isRequired,
}

export async function getStaticProps() {
  const collections = await collectionService.loadAllCollections()

  const websiteData = await websiteService.loadWebsiteInformation()

  return {
    props: {
      collections,
      description: websiteData.description,
    },
  }
}

export default Home
